title: MiPnamic Von Wirklichkeit
email: mipnamic@mipnamic.net
description: >
  Bearded Developer and Enthusiast<br/>made in Italy
baseurl: ""
url: https://mipnamic.net
author: "Marco Orlandin"
avatar: "https://www.gravatar.com/avatar/c22b20d403db75d9a842e1a34bf2c479.png?s=200"
og:
  url: https://mipnamic.net/index.html
  title: Bearded Developerand Enthusiast
  image: https://mipnamic.net/img/mipnamicfb.jpg
  locale: en_US
  description: >
    MiPnamic Von Wirklichkeit aka Marco Orlandin - Bearded Developer and Enthusiast made in Italy.
social:
  instagram: https://instagram.com/MiPnamic
  github: https://github.com/MiPnamic
  codepen: https://codepen.io/MiPnamic
  linkedin: https://it.linkedin.com/in/mipnamic
  twitter: https://twitter.com/MiPnamic
  facebook: https://www.facebook.com/MiPnamic
excerpt_separator: <!--more-->
extrainfo:
  - IT 02424420020
buymeabeer: https://www.paypal.me/mipnamic/3

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
theme: mvw33
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock